#!/usr/bin/env node
// Builds the package from src/icons.mjs. No dependencies.
//
//   dist/svg/<name>.svg          standalone files (24×24, currentColor)
//   dist/sprite.svg              <symbol id="mbx-<name>"> sheet for the web
//   dist/icons.json              manifest: name, category, keywords, elements
//   dist/index.js / .d.ts        core: names, markup map, element lists, svg()
//   dist/react/index.js / .d.ts  React DOM: <MbxIcon name> + PascalCase exports
//   dist/react-native/…          react-native-svg: same API
//   docs/preview.html            browsable contact sheet

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { icons, CATEGORIES, CATEGORY_ICONS, GRID, STROKE_WIDTH } from '../src/icons.mjs';
import { renderPreview } from './preview.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
rmSync(dist, { recursive: true, force: true });
for (const d of ['svg', 'react', 'react-native']) mkdirSync(join(dist, d), { recursive: true });
mkdirSync(join(root, 'docs'), { recursive: true });

const ALLOWED_TAGS = new Set(['path', 'circle', 'rect', 'line']);
const ROOT_ATTRS = `xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GRID} ${GRID}" width="${GRID}" height="${GRID}" fill="none" stroke="currentColor" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round"`;

// ── validate + parse ───────────────────────────────────────────────
const seen = new Set();
const parseBody = (icon) => {
  const elements = [];
  const re = /<(\w+)([^>]*?)\/>/g;
  let m, consumed = '';
  while ((m = re.exec(icon.body))) {
    const [, tag, rawAttrs] = m;
    consumed += m[0];
    if (!ALLOWED_TAGS.has(tag)) throw new Error(`${icon.name}: <${tag}> is not allowed`);
    const attrs = {};
    for (const a of rawAttrs.matchAll(/([\w-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    if (attrs.fill && attrs.fill !== 'currentColor') throw new Error(`${icon.name}: fill must be currentColor`);
    if (attrs.stroke || attrs.style || attrs.class) throw new Error(`${icon.name}: no stroke/style/class per element`);
    for (const n of Object.values(attrs).join(' ').match(/-?\d+(\.\d+)?/g) ?? []) {
      if (Math.abs(+n) > 40) throw new Error(`${icon.name}: coordinate ${n} is far outside the grid`);
    }
    elements.push({ tag, attrs });
  }
  if (consumed.replace(/\s/g, '') !== icon.body.replace(/\s/g, '')) throw new Error(`${icon.name}: body has markup that is not a self-closing element`);
  if (!elements.length) throw new Error(`${icon.name}: empty body`);
  return elements;
};

const manifest = icons.map((icon) => {
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(icon.name)) throw new Error(`bad name: ${icon.name}`);
  if (seen.has(icon.name)) throw new Error(`duplicate icon: ${icon.name}`);
  seen.add(icon.name);
  if (!CATEGORIES[icon.category]) throw new Error(`${icon.name}: unknown category ${icon.category}`);
  if (!Array.isArray(icon.keywords) || !icon.keywords.length) throw new Error(`${icon.name}: needs keywords`);
  return { name: icon.name, category: icon.category, keywords: icon.keywords, elements: parseBody(icon), body: icon.body.trim() };
});

for (const [path, name] of Object.entries(CATEGORY_ICONS)) {
  if (!seen.has(name)) throw new Error(`CATEGORY_ICONS: ${path} → ${name} is not an icon`);
  if (!/^[a-z0-9-]+(\/[a-z0-9-]+){0,2}$/.test(path)) throw new Error(`CATEGORY_ICONS: bad path ${path}`);
}

const pascal = (s) => s.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// ── standalone SVGs + sprite + manifest ────────────────────────────
for (const i of manifest) writeFileSync(join(dist, 'svg', `${i.name}.svg`), `<svg ${ROOT_ATTRS}>${i.body}</svg>\n`);
writeFileSync(join(dist, 'sprite.svg'), [
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
  ...manifest.map((i) => `  <symbol id="mbx-${i.name}" viewBox="0 0 ${GRID} ${GRID}" fill="none" stroke="currentColor" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round">${i.body}</symbol>`),
  `</svg>`, '',
].join('\n'));
writeFileSync(join(dist, 'icons.json'), JSON.stringify({ grid: GRID, strokeWidth: STROKE_WIDTH, categories: CATEGORIES, categoryIcons: CATEGORY_ICONS, icons: manifest.map(({ body, ...r }) => r) }, null, 2) + '\n');

// ── core ───────────────────────────────────────────────────────────
// Element attrs are stored with React-style camelCase keys (strokeDasharray);
// the core `svg()` helper converts back to kebab-case for markup.
const elementsByName = Object.fromEntries(manifest.map((i) => [i.name, i.elements.map((e) => ({ tag: e.tag, attrs: Object.fromEntries(Object.entries(e.attrs).map(([k, v]) => [camel(k), v])) }))]));
const nameUnion = manifest.map((i) => JSON.stringify(i.name)).join(' | ');

writeFileSync(join(dist, 'index.js'), [
  `// Generated by scripts/build.mjs — do not edit.`,
  `export const GRID = ${GRID};`,
  `export const STROKE_WIDTH = ${STROKE_WIDTH};`,
  `export const ROOT_ATTRS = ${JSON.stringify(ROOT_ATTRS)};`,
  `export const CATEGORIES = ${JSON.stringify(CATEGORIES)};`,
  `export const ELEMENTS = ${JSON.stringify(elementsByName)};`,
  `export const META = ${JSON.stringify(Object.fromEntries(manifest.map((i) => [i.name, { category: i.category, keywords: i.keywords }])))};`,
  `export const names = Object.keys(ELEMENTS);`,
  `/** service_categories.path → icon name (see src/icons.mjs). */`,
  `export const CATEGORY_ICONS = ${JSON.stringify(CATEGORY_ICONS)};`,
  `/** Icon for a category path, falling back to the nearest mapped ancestor, then \`fallback\`. */`,
  `export const categoryIcon = (path, fallback = 'haircut') => { const parts = String(path || '').split('/'); while (parts.length) { const hit = CATEGORY_ICONS[parts.join('/')]; if (hit) return hit; parts.pop(); } return fallback; };`,
  `const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());`,
  `/** Inner markup for one icon (no <svg> wrapper). */`,
  `export const body = (name) => { const els = ELEMENTS[name]; if (!els) throw new Error('Unknown MBX icon: ' + name); return els.map((e) => '<' + e.tag + Object.entries(e.attrs).map(([k, v]) => ' ' + kebab(k) + '="' + v + '"').join('') + '/>').join(''); };`,
  `/** Full standalone <svg> markup for one icon; extra attrs are appended to the root. */`,
  `export const svg = (name, attrs = '') => '<svg ' + ROOT_ATTRS + (attrs ? ' ' + attrs : '') + '>' + body(name) + '</svg>';`,
  '',
].join('\n'));
writeFileSync(join(dist, 'index.d.ts'), [
  `export type MbxIconName = ${nameUnion};`,
  `export type MbxCategory = ${Object.keys(CATEGORIES).map((c) => JSON.stringify(c)).join(' | ')};`,
  `export interface MbxElement { tag: 'path' | 'circle' | 'rect' | 'line'; attrs: Record<string, string>; }`,
  `export declare const GRID: number;`,
  `export declare const STROKE_WIDTH: number;`,
  `export declare const ROOT_ATTRS: string;`,
  `export declare const CATEGORIES: Record<MbxCategory, string>;`,
  `export declare const ELEMENTS: Record<MbxIconName, MbxElement[]>;`,
  `export declare const META: Record<MbxIconName, { category: MbxCategory; keywords: string[] }>;`,
  `export declare const names: MbxIconName[];`,
  `export type MbxCategoryPath = ${Object.keys(CATEGORY_ICONS).map((c) => JSON.stringify(c)).join(' | ')};`,
  `export declare const CATEGORY_ICONS: Record<MbxCategoryPath, MbxIconName>;`,
  `export declare function categoryIcon(path: string | null | undefined, fallback?: MbxIconName): MbxIconName;`,
  `export declare function body(name: MbxIconName): string;`,
  `export declare function svg(name: MbxIconName, attrs?: string): string;`,
  '',
].join('\n'));

// ── React (DOM) and React Native — same component, different primitives ──
const componentSource = (platform) => {
  const imports = platform === 'dom'
    ? `import { createElement, forwardRef } from 'react';\nconst TAGS = { path: 'path', circle: 'circle', rect: 'rect', line: 'line' };\nconst ROOT = 'svg';`
    : `import { createElement, forwardRef } from 'react';\nimport Svg, { Path, Circle, Rect, Line } from 'react-native-svg';\nconst TAGS = { path: Path, circle: Circle, rect: Rect, line: Line };\nconst ROOT = Svg;`;
  return [
    `// Generated by scripts/build.mjs — do not edit.`,
    imports,
    `import { ELEMENTS, GRID, STROKE_WIDTH } from '../index.js';`,
    `export { ELEMENTS, GRID, STROKE_WIDTH, names, CATEGORIES, META, CATEGORY_ICONS, categoryIcon } from '../index.js';`,
    ``,
    `/**`,
    ` * <MbxIcon name="fade" size={24} color="#1B1F2A" strokeWidth={1.75} />`,
    ` * color defaults to currentColor${platform === 'dom' ? ' (inherits CSS color)' : ' — pass a colour explicitly in React Native'}.`,
    ` */`,
    `export const MbxIcon = forwardRef(function MbxIcon({ name, size = GRID, color = 'currentColor', strokeWidth = STROKE_WIDTH, absoluteStrokeWidth = false, ...rest }, ref) {`,
    `  const els = ELEMENTS[name];`,
    `  if (!els) { if (typeof __DEV__ === 'undefined' || __DEV__) console.warn('Unknown MBX icon: ' + name); return null; }`,
    `  const sw = absoluteStrokeWidth ? (strokeWidth * GRID) / size : strokeWidth;`,
    `  return createElement(ROOT, { ref, ${platform === 'dom' ? 'xmlns: "http://www.w3.org/2000/svg", ' : ''}width: size, height: size, viewBox: '0 0 ' + GRID + ' ' + GRID, fill: 'none', stroke: color, strokeWidth: sw, strokeLinecap: 'round', strokeLinejoin: 'round', ${platform === 'dom' ? `'aria-hidden': rest['aria-label'] ? undefined : true, ` : ''}...rest },`,
    `    els.map((e, k) => { const a = { ...e.attrs, key: k }; if (a.fill === 'currentColor') a.fill = color; return createElement(TAGS[e.tag], a); }));`,
    `});`,
    `export default MbxIcon;`,
    ``,
    `// One component per icon, lucide-style: import { Scissors } from '@mbx/icons/react'`,
    ...manifest.map((i) => `export const ${pascal(i.name)} = forwardRef((p, ref) => createElement(MbxIcon, { ...p, ref, name: ${JSON.stringify(i.name)} })); ${pascal(i.name)}.displayName = ${JSON.stringify(pascal(i.name))};`),
    '',
  ].join('\n');
};
const componentTypes = (platform) => [
  `import type { ForwardRefExoticComponent, RefAttributes${platform === 'dom' ? ', SVGProps' : ''} } from 'react';`,
  platform === 'dom' ? '' : `import type Svg from 'react-native-svg';\nimport type { SvgProps } from 'react-native-svg';`,
  `import type { MbxIconName } from '../index';`,
  `export type { MbxIconName, MbxCategory, MbxElement } from '../index';`,
  `export { ELEMENTS, GRID, STROKE_WIDTH, names, CATEGORIES, META, CATEGORY_ICONS, categoryIcon } from '../index';`,
  `export type { MbxCategoryPath } from '../index';`,
  platform === 'dom'
    ? `type BaseProps = Omit<SVGProps<SVGSVGElement>, 'ref' | 'color' | 'name'> & RefAttributes<SVGSVGElement>;`
    : `type BaseProps = Omit<SvgProps, 'color' | 'name'> & RefAttributes<Svg>;`,
  `export interface MbxIconStyleProps { size?: number | string; color?: string; strokeWidth?: number; /** keep the stroke at strokeWidth px regardless of size */ absoluteStrokeWidth?: boolean; }`,
  `export interface MbxIconProps extends BaseProps, MbxIconStyleProps { name: MbxIconName; }`,
  `export type MbxIconComponent = ForwardRefExoticComponent<BaseProps & MbxIconStyleProps>;`,
  `export declare const MbxIcon: ForwardRefExoticComponent<MbxIconProps>;`,
  `export default MbxIcon;`,
  ...manifest.map((i) => `export declare const ${pascal(i.name)}: MbxIconComponent;`),
  '',
].join('\n');
writeFileSync(join(dist, 'react', 'index.js'), componentSource('dom'));
writeFileSync(join(dist, 'react', 'index.d.ts'), componentTypes('dom'));
writeFileSync(join(dist, 'react-native', 'index.js'), componentSource('native'));
writeFileSync(join(dist, 'react-native', 'index.d.ts'), componentTypes('native'));

// ── preview ────────────────────────────────────────────────────────
writeFileSync(join(root, 'docs', 'preview.html'), renderPreview({ manifest, categories: CATEGORIES, categoryIcons: CATEGORY_ICONS, grid: GRID, strokeWidth: STROKE_WIDTH, rootAttrs: ROOT_ATTRS }));

console.log(`built ${manifest.length} icons → dist/ and docs/preview.html`);
